ARG BASE_IMAGE=scratch

FROM golang:1.15.8 AS build
ARG GOPROXY
ENV GOPROXY $GOPROXY

WORKDIR /go/src/code.cloudfoundry.org/quarks-secret

# Copy the rest of the source code and build
COPY . .
RUN [ -f tools/quarks-utils/bin/include/versioning ] || \
    bin/tools
RUN bin/build && \
    cp -p binaries/quarks-secret /usr/local/bin/quarks-secret

FROM $BASE_IMAGE
LABEL org.opencontainers.image.source https://github.com/cloudfoundry-incubator/quarks-secret
COPY --from=build /usr/local/bin/quarks-secret /usr/local/bin/quarks-secret
ENTRYPOINT ["/usr/local/bin/quarks-secret"]
