kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: quarkssecrets.quarks.cloudfoundry.org
spec:
  group: quarks.cloudfoundry.org
  names:
    plural: quarkssecrets
    singular: quarkssecret
    shortNames:
      - qsec
      - qsecs
    kind: QuarksSecret
    listKind: QuarksSecretList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - secretName
                - type
              properties:
                copies:
                  description: A list of namespaced names where to copy generated secrets
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                request:
                  type: object
                  properties:
                    templatedConfig:
                      description: >-
                        TemplatedConfig renders the template map into the
                        generated secret
                      type: object
                      properties:
                        templates:
                          description: >-
                            Template values to interpolate in the generated
                            secret
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        type:
                          description: Type of template being used (helm)
                          type: string
                        values:
                          description: >-
                            Template values to interpolate in the generated
                            secret
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                  x-kubernetes-preserve-unknown-fields: true
                secretAnnotations:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                secretLabels:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                secretName:
                  description: The name of the generated secret
                  type: string
                  minLength: 1
                type:
                  description: >-
                    What kind of secret to generate: password, certificate, ssh,
                    rsa
                  type: string
                  minLength: 1
            status:
              type: object
              properties:
                copied:
                  type: boolean
                generated:
                  type: boolean
                lastReconcile:
                  type: string
                  nullable: true
  conversion:
    strategy: None